) Data Analytics III
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on
the given dataset.

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB

In [ ]:
data=pd.read_csv("iris.csv")

In [ ]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
data.shape

(150, 5)

In [ ]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
data.notnull().sum()

sepal_length    150
sepal_width     150
petal_length    150
petal_width     150
species         150
dtype: int64

In [ ]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
x=data.drop(['species'],axis=1)
y=data['species']

In [ ]:
x_train,x_test,y_train,y_test= train_test_split(x, y, test_size = 0.20, random_state=0)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [ ]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [ ]:
x_train

array([[ 0.61303014,  0.10850105,  0.94751783,  0.73603967],
       [-0.56776627, -0.12400121,  0.38491447,  0.34808318],
       [-0.80392556,  1.03851009, -1.30289562, -1.3330616 ],
       [ 0.25879121, -0.12400121,  0.60995581,  0.73603967],
       [ 0.61303014, -0.58900572,  1.00377816,  1.25331499],
       [-0.80392556, -0.82150798,  0.04735245,  0.21876435],
       [-0.21352735,  1.73601687, -1.19037495, -1.20374277],
       [ 0.14071157, -0.82150798,  0.72247648,  0.47740201],
       [ 0.02263193, -0.12400121,  0.21613346,  0.34808318],
       [-0.09544771, -1.05401024,  0.10361279, -0.03987331],
       [ 1.0853487 , -0.12400121,  0.94751783,  1.12399616],
       [-1.39432376,  0.34100331, -1.41541629, -1.3330616 ],
       [ 1.20342834,  0.10850105,  0.72247648,  1.38263382],
       [-1.04008484,  1.03851009, -1.24663528, -0.81578628],
       [-0.56776627,  1.50351461, -1.30289562, -1.3330616 ],
       [-1.04008484, -2.4490238 , -0.1776889 , -0.29851096],
       [ 0.73110978, -0.

In [ ]:
x_test

array([[ 0.14956537, -0.58304897,  0.94512598,  1.91948971],
       [ 0.43000045, -1.9460206 ,  0.2829358 , -0.10102577],
       [-0.27108724,  2.59721815, -1.28224097, -1.25560605],
       [ 2.25282843, -0.35588703,  1.66751526,  1.0535545 ],
       [-0.97217492,  0.77992265, -1.22204187, -1.25560605],
       [ 0.85065306,  0.55276071,  1.48691794,  2.06381224],
       [-0.97217492,  1.00708459, -1.34244008, -1.11128352],
       [ 1.41152321,  0.09843684,  0.70432955,  0.6205869 ],
       [ 1.55174074, -0.58304897,  0.76452866,  0.47626436],
       [ 0.57021798, -0.58304897,  0.2829358 ,  0.33194183],
       [ 0.57021798, -1.03737285,  1.24612151,  0.47626436],
       [ 0.9908706 ,  0.32559878,  0.58393134,  0.6205869 ],
       [ 0.57021798, -0.58304897,  0.70432955,  0.18761929],
       [ 1.13108813, -0.58304897,  0.64413044,  0.6205869 ],
       [ 0.57021798, -0.35588703,  0.70432955,  0.47626436],
       [-1.11239246,  0.09843684, -1.22204187, -1.39992858],
       [ 0.43000045, -0.

In [ ]:
goss=GaussianNB()
goss.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred_test=goss.predict(x_test)

In [ ]:
y_pred_test

array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'versicolor',
       'virginica', 'virginica', 'versicolor', 'virginica', 'virginica',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'versicolor', 'setosa', 'setosa', 'virginica',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'setosa'],
      dtype='<U10')

In [ ]:
confusion_matrix(y_test,y_pred_test)

array([[11,  0,  0],
       [ 0,  7,  6],
       [ 0,  0,  6]], dtype=int64)

In [ ]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      0.54      0.70        13
   virginica       0.50      1.00      0.67         6

    accuracy                           0.80        30
   macro avg       0.83      0.85      0.79        30
weighted avg       0.90      0.80      0.80        30



In [ ]:
print("Accuracy : ", accuracy_score(y_test, y_pred_test))

Accuracy :  0.8
